[book]
authors = ["liushan"]
language = "zh-CN"
multilingual = false
src = "blog-src"
title = "shanliu blog"

[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = false


[output.html]
mathjax-support = true
site-url = "/blog/"
curly-quotes = true
git-repository-url = "https://github.com/shanliu"

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
